export const ON_DROP_FILES = 'ON_DROP_FILES';
export const HANDLE_CHANGE_FOOD_NAME = 'HANDLE_CHANGE_FOOD_NAME';
export const HANDLE_EDITOR_CHANGE = 'HANDLE_EDITOR_CHANGE';
export const SUBMIT_DATA = 'SUBMIT_DATA';